undefine(`len')
define(`FUNCTION',`$1_')
define(`STRING_ARG',`char *$1_ptr, int *$1_len')
define(`STRING_ARG_DECL',`')
define(`STRING_LEN',`(*$1_len)')
define(`STRING_PTR',`$1_ptr')
define(`ARGS',`($1)')
